version: '3'

services:
  db_test:
    image: postgres:13
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=test
      - POSTGRES_DB=oklm_test
    restart: always
    container_name: oklm_db_tests
    ports:
      - 5433:5432
