name: CD-Staging on clevercloud

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  dependencies:
    uses: ./.github/workflows/_dependencies.reusable.yml
    with:
      node-version: '16.13.1'

#  build:
#    needs: dependencies
#    uses: ./.github/workflows/_build-static-bundle.reusable.yml
#    with:
#      build-directory-path: 'dist/oklm'

  validation:
    needs: dependencies
    uses: ./.github/workflows/_validation.reusable.yml

#  deploy:
#    needs:
#      - build
#      - validation
#    uses: ./.github/workflows/_deploy-static-application.clevercloud.reusable.yml
#    with:
#      application-full-name: 'oklm-staging'
#    secrets:
#      CLEVER_ORG_ID: ${{ secrets.CLEVER_ORG_ID }}
#      CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
#      CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
#
#  notify:
#    needs:
#      - deploy
#    uses: ./.github/workflows/_notify-deployment.mattermost.reusable.yml
#    with:
#      application-full-name: 'oklm-staging'
#      deployed-domain: ${{ needs.deploy.outputs.deployed-domain }}
#    secrets:
#      MATTERMOST_NOTIFY_HOOK_URL: ${{ secrets.MATTERMOST_NOTIFY_HOOK_URL }}
